# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARvAxJ1QrMMGduieia7Yliu7IEpATmyp
"""

import streamlit as st
import joblib

# Load model and label encoder
model = joblib.load("yield_predictor_model.pkl")
label_encoder = joblib.load("crop_label_encoder.pkl")

# Streamlit app layout
st.title("🌾 Crop Yield Predictor")
st.markdown("Enter the crop details below to estimate the crop yield (hg/ha).")

# User inputs
with st.form(key='yield_form'):
    crop_name = st.selectbox("Crop Type", label_encoder.classes_)
    year = st.slider("Year", min_value=1990, max_value=2030, value=2010)
    pesticides = st.number_input("Pesticide Usage (tonnes)", min_value=0.0, value=35000.0)
    avg_temp = st.slider("Average Temperature (°C)", min_value=10.0, max_value=30.0, value=18.5)
    submit_button = st.form_submit_button(label='Predict Yield')

# Prediction logic
if submit_button:
    try:
        crop_encoded = label_encoder.transform([crop_name])[0]
        input_data = [[crop_encoded, year, pesticides, avg_temp]]
        predicted_yield = model.predict(input_data)[0]
        st.success(f"✅ Predicted Yield for {crop_name} in {year}: {predicted_yield:.2f} hg/ha")
    except Exception as e:
        st.error(f"Error: {str(e)}")
